# Generated by Django 5.2.17 on 2026-09-02 12:41

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'constraints': [models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='product_sku_non_empty'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_name_non_empty'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='product_unit_price_non_negative')],
            },
        ),
    ]
