# Generated by Django 5.2.17 on 2026-09-02 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=32)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_events', to='orders.salesorder')),
            ],
            options={
                'db_table': 'integration_external_events',
                'constraints': [models.CheckConstraint(condition=models.Q(('processing_status__in', ['RECEIVED', 'PROCESSED', 'FAILED'])), name='externalevent_valid_processing_status'), models.CheckConstraint(condition=models.Q(('payment_amount__isnull', True), ('payment_amount__gte', 0), _connector='OR'), name='externalevent_payment_amount_non_negative')],
            },
        ),
    ]
