# Generated by Django 5.2.17 on 2026-09-02 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('reserved_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_items',
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='stockitem_product_warehouse_unique'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stockitem_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='stockitem_reserved_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='stockitem_reserved_lte_quantity')],
            },
        ),
    ]
